[k8s_cluster:children]
kube_control_plane
kube_node

[kube_control_plane]
k8s-master-1 ansible_host=192.168.100.20

[kube_node]
k8s-worker-1 ansible_host=192.168.100.21

[mgmt_node]
mgmt-1 ansible_host=192.168.100.10

[all:vars]
ansible_user=rocky
# ansible_ssh_pass=your_password
# ansible_ssh_private_key_file=~/.ssh/id_rsa